### ISSUE TITLE
Free Downloads Integration

### ISSUE THREAD

**Issue by kerijacoby** [easydigitaldownloads/edd-custom-prices#4]
Current Scenario:
The Free Download extension is also active
$0 is the minimum price allowed
Customer chooses $0 and is directed to the checkout page

Proposal:
Customer chooses $0 and Free Downloads takes over

Related ticket: https://secure.helpscout.net/conversation/537428388/77746?folderId=180504

**Comment by cklosowski** [comment]
We actually have this open as an issue on Free Downloads already:
https://github.com/easydigitaldownloads/edd-free-downloads/issues/133
